### ISSUE TITLE
Empty filename default

### ISSUE THREAD

**Issue by goatandsheep** [parshap/node-sanitize-filename#27]
* If a file contains only illegal characters, it should be defaulted to something, perhaps "file"
* If a file contains an illegal name before the last period (i.e. extension), it should be defaulted to something, perhaps "file.extension"

**Comment by parshap** [comment]
> If a file contains only illegal characters, it should be defaulted to something, perhaps "file"

I've left it up to the caller to set a default value -  `sanitize(fileName) || "file"`. There is [a section about this in the readme](
https://github.com/parshap/node-sanitize-filename#empty-string--result), but maybe it can be improved.

> If a file contains an illegal name before the last period (i.e. extension), it should be defaulted to something, perhaps "file.extension"

Are you saying if a file name `??.jpg` is given, `file.jpg` should be returned (instead of `.jpg` currently), reserving the extension and ensuring a name part (`file`)? I feel this logic is a bit specific and best left for the caller to implement.

**Comment by goatandsheep** [comment]
@parshap good point! I agree that it should be up to the caller to implement
