### ISSUE TITLE
Reserved filenames in Windows

### ISSUE THREAD

**Issue by joelmukuthu** [parshap/node-sanitize-filename#9]
Similarly to stripping out unix-reserved filenames, shouldn't this also handle windows reserved filenames? [Ref](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)

**Comment by parshap** [comment]
Are you referring to the following list?

> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

That sounds like a good idea!

**Comment by joelmukuthu** [comment]
I'm glad you think so! I've [implemented this](https://github.com/joelmukuthu/node-sanitize-filename/blob/master/index.js) and [added tests](https://github.com/joelmukuthu/node-sanitize-filename/blob/master/test.js) for it too. Will submit a PR.

However I haven't added tests that actually try to write those filenames to the file system, mostly because I'm not running a Windows installation. I'll navigate around that soon!

**Comment by joelmukuthu** [comment]
Thinking about this further, it might be better to make this stripping out optional, perhaps using the options passed in. What do you think?

**Comment by parshap** [comment]
For the benefit of non-Windows users? I've thought about this too, because different operating systems and different filesystems have different rules about what is a valid filename. We could let the user pass in a "target" system (e.g., "windows", or "fat32") and only sanitize against that system's rule.

That said, I think the default behavior should still be to sanitize against *all* systems. It seems like a safe default for users that don't bother to look at the options. It also handles the common use case of naming files that will be shared across systems (e.g., files served via http).

**Comment by joelmukuthu** [comment]
Yes, I agree that we should let the targets be configurable, though perhaps we could go with an object instead of a string, something like:
```javascript
target: {
    unix: true,
    ntfs: false,
    fat32: false
}
``` 
Which would allow someone to sanitize against more than one target. And I agree that the default should be true for all targets.

**Comment by parshap** [comment]
I like it. I'm going to open an issue for this functionality so the idea doesn't get lost in this closed PR.

**Comment by joelmukuthu** [comment]
Perfect!
